"""
Runs every model, the invariant self-checks, and writes:
  analysis/results.json  - consumed by build.js, so every number in the annexures is computed
  analysis/RESULTS.md    - human-readable summary for reviewers / the applicant
Exit code 1 if any self-check fails.
"""
import json
import sys
from pathlib import Path
import numpy as np

from . import params as P
from . import survival, calibration, latency, geometry, multijammer, survivability, checks

OUT = Path(__file__).resolve().parent


def _clean(o):
    if isinstance(o, dict):
        return {str(k): _clean(v) for k, v in o.items()}
    if isinstance(o, (list, tuple)):
        return [_clean(v) for v in o]
    if isinstance(o, (np.floating,)):
        return float(o)
    if isinstance(o, (np.integer,)):
        return int(o)
    if isinstance(o, np.ndarray):
        return _clean(o.tolist())
    if isinstance(o, float) and (o != o or o in (float("inf"), float("-inf"))):
        return None
    return o


def main():
    res = {}
    res["checks"] = checks.run_all()
    rng = np.random.default_rng(5)
    res["fixed_point"] = dict(floor_db=checks.fixed_point_floor_db(rng),
                              threshold_db=-50.0,
                              min_detectable_corruption_deg=checks.min_detectable_corruption_deg(rng))
    res["geometry"] = geometry.compare()
    res["calibration"] = calibration.summary()
    sv = survival.summary()
    # TILT_MAX from the DoA sigma actually achieved at K, JNR 20 dB
    sig = res["calibration"]["sigma_kxy_at_K_20db"]
    el_err, tilt = survival.tilt_observability(sigma_kxy=sig, target_err_deg=sv["tol30_deg"]["min"] / 2)
    sv["tilt"] = dict(sigma_kxy=sig, el_err_deg=float(el_err), tilt_max_deg=float(tilt))
    sv["stale_vs_span"] = survival.stale_weight_vs_span()
    res["survival"] = sv
    res["latency"] = latency.summary()
    res["multijammer"] = multijammer.summary()
    res["survivability"] = survivability.summary()
    res["params"] = dict(array=P.ARRAY, r_mm=P.spacing_m() * 1e3, fs_hz=P.FS_HZ, K=P.OBS["K"],
                         clocks=P.CLOCKS, hw=P.HW, link=P.LINK, drdo=P.DRDO, failsafe=P.FAILSAFE,
                         timing=P.TIMING_SCENARIOS, pipe=P.PIPE, caseb=P.CASEB, imu=P.IMU,
                         platform=P.PLATFORM, jammer=P.JAMMER)
    res = _clean(res)
    (OUT / "results.json").write_text(json.dumps(res, indent=1))
    (OUT / "RESULTS.md").write_text(report(res))
    failed = [c["name"] for c in res["checks"] if not c["ok"]]
    print(f"self-checks: {len(res['checks']) - len(failed)}/{len(res['checks'])} pass")
    if failed:
        print("FAILED:", *failed, sep="\n  ")
        sys.exit(1)


def report(r):
    sv, lat, sb, cal, mj = r["survival"], r["latency"], r["survivability"], r["calibration"], r["multijammer"]
    L = []
    a = L.append
    a("# HOPNULL-ARC - analysis results\n")
    a("Generated by `python3 -m analysis.run_all`. Every number quoted in the annexures comes from this run.\n")
    a("## Invariant self-checks\n")
    for c in r["checks"]:
        a(f"- [{'x' if c['ok'] else ' '}] {c['name']}")
    fp = r["fixed_point"]
    a(f"\n16-bit weight null floor {fp['floor_db']:.1f} dB; self-check threshold {fp['threshold_db']:.0f} dB; "
      f"catches any single-weight corruption >= {fp['min_detectable_corruption_deg']:.2f} deg.\n")
    a("## Array geometry trade (4 elements, GCS and jammer near the horizon)\n")
    a("| Geometry | 3-D direction observable | Defended azimuth (worst GCS bearing) | Median gain after null |")
    a("|---|---|---|---|")
    for g in r["geometry"]:
        a(f"| {g['name']} | {'yes' if g['obs3d'] else 'no (cone angle only)'} | {g['defended_worst_pct']:.0f}% | {g['gain_median_db']:.1f} dB |")
    a("\n## Null survival (30 dB rejection held without refresh)\n")
    t = sv["tol30_deg"]
    a(f"Pointing tolerance for 30 dB: worst {t['min']:.2f} deg, median {t['median']:.2f} deg over defended geometries.\n")
    a(f"- Body-frame hold (stored weights / airframe tracking), 20 deg/s turn: {sv['t_body_turn_ms']:.0f} ms worst, {sv['t_body_turn_med_ms']:.0f} ms median; at 60 deg/s: {sv['t_body_maxrate_ms']:.1f} ms")
    a("\n| Jammer range | LOS rate (30+30 m/s) | Earth-frame hold (worst) | vs body-frame at 20 deg/s |")
    a("|---|---|---|---|")
    for row in sv["survival_table"]:
        a(f"| {row['range_km']:.0f} km | {row['los_rate_dps']:.2f} deg/s | {row['t_earth_s']:.2f} s | {row['ratio_vs_turn']:.0f}x |")
    fh = sv["fiism_hit"]
    a(f"\nFIISM sub-band revisit hit-rate at {fh['hop_rate']:.0f} hop/s, {fh['n_subbands']} sub-bands: body-frame aging {100*fh['p_body']:.0f}% vs earth-frame {100*fh['p_earth']:.0f}%.")
    a(f"Tilt observability: DoA sigma {sv['tilt']['sigma_kxy']:.4f} -> elevation error {sv['tilt']['el_err_deg']:.2f} deg -> TILT_MAX {sv['tilt']['tilt_max_deg']:.0f} deg.\n")
    a("Stale weights reused across a hop span (what per-band weight storage does):\n")
    for row in sv["stale_vs_span"]:
        a(f"- span {row['span_pct']:.0f}%: median {row['median_db']:.1f} dB, p10 {row['p10_db']:.1f} dB")
    a("\n## Calibration and observation window\n")
    a("| RMS phase error | Median rejection | 10th percentile |")
    a("|---|---|---|")
    for row in cal["cal"]:
        a(f"| {row['phase_rms_deg']:g} deg | {row['median_db']:.1f} dB | {row['p10_db']:.1f} dB |")
    a(f"\n30 dB on 90% of geometries needs <= {cal['phase_budget_30db_p10_deg']:g} deg RMS. "
      f"K = {cal['K']} ({cal['T_obs_us']:.1f} us): residual J/N after nulling ~ "
      f"{np.mean([x['residual_jn_db'] for x in cal['residual_jn_at_K']]):.0f} dB, independent of JNR.\n")
    a("## Latency budget (derated x2)\n")
    for tag in ("fpga", "asic"):
        b = lat[f"budget_{tag}"]
        a(f"- {tag.upper()}: B1 {b['B1']} + B2 {b['B2']} + B3 {b['B3']} = {b['raw_cycles']} cycles raw -> {b['T_B_us']:.1f} us; "
          f"max hop rate {lat[f'max_hop_{tag}']:.0f} hop/s (V1), {lat[f'max_hop_{tag}_v2']:.0f} hop/s (V2)")
    a("\n| Scenario (ASIC) | T_hop | G | TC1 slack | TC1 util. | TC2 slack | settle slack (NCO / PLL) |")
    a("|---|---|---|---|---|---|---|")
    for m, pll in zip(lat["margins_asic"], lat["pll_settle_check"]):
        a(f"| {m['name']} {m['hop_rate']:.0f}/s | {m['T_hop_us']:.0f} us | {m['G_us']:.0f} us | {m['T1_slack_us']:.0f} us | {100*m['T1_util']:.0f}% | {m['T2_slack_us']:.0f} us | {m['settle_slack_us']:.1f} / {pll['settle_slack_us']:.0f} us |")
    a("\nCase B (no hop sideband):\n")
    for c in lat["case_b"]:
        a(f"- {c['hop_rate']:.0f} hop/s: coast {c['n_coast_hops']} hops ({c['coast_ms']:.0f} ms) between re-locks; unprotected {100*c['unprotected_frac']:.1f}% of dwell")
    a(f"- sub-band-centre weight table: worst {lat['subband_rejection_db'][0]:.1f} dB at the sub-band edge")
    a(f"- CLZ gain step: {lat['gain_step_db']['lut0']:.2f} dB without LUT, {lat['gain_step_db']['lut3']:.2f} dB with 16-entry LUT")
    bg = lat["v2_background_asic"]
    a(f"\nV2 background (EVD + {bg['music_evals']}-point grid MUSIC): {bg['time_us']:.0f} us at 50 MHz -> "
      + ", ".join(f"{x['hops']} hop(s) at {x['hop_rate']:.0f}/s" for x in bg["per_scenario"]))
    a("\n## V2 dual-jammer path\n")
    mc = mj["mc"]
    a(f"{mc['detected_2']}/{mc['trials']} two-jammer cases detected; rejection of the worse jammer at f(n+1): "
      f"median {mc['median_db']:.1f} dB, p10 {mc['p10_db']:.1f} dB; V1 gates refused {mc['v1_refused']}/{mc['trials']} "
      f"(the rest had one jammer >= 10 dB dominant).\n")
    a("## Survivability (DRDO 5 km reference link)\n")
    lb = sb["link"]
    a(f"Link: FSPL {lb['fspl_db']:.1f} dB, SNR {lb['SNR_db']:.1f} dB after {P.LINK['fade_margin_db']:.0f} dB fade margin, margin {lb['margin_db']:.1f} dB over required SINR.")
    a(f"Effective protection {sb['power_multiplier_db']:.1f} dB (30 dB rejection + {sb['gain_after_null_db']['median']:.1f} dB kept array gain) -> "
      f"denial range / {sb['range_divisor']:.0f}; tolerable JNR {sb['max_jnr_db']['with_hopnull']:.0f} dB vs {sb['max_jnr_db']['without']:.0f} dB.\n")
    a("| Jammer EIRP | Spot, unprotected | Spot, HOPNULL-ARC | Barrage, unprotected | Barrage, HOPNULL-ARC |")
    a("|---|---|---|---|---|")
    for row in sb["burn_through"]:
        a(f"| {row['w_eirp']:g} W | {min(row['spot_no_null_km'], sb['horizon_km']):.1f} km | {row['spot_null_km']:.2f} km | {min(row['barrage_no_null_km'], sb['horizon_km']):.1f} km | {row['barrage_null_km']:.2f} km |")
    fo = sb["follower"]
    a(f"\nFollower jammer ({fo['delay_us']:.0f} us reaction): covers {100*fo['covered_frac']:.0f}% of a 1 ms dwell; FHSS alone would need {fo['fhss_only_hop_rate_needed']:.0f} hop/s.")
    fs = sb["failsafe"]
    a(f"Fail-to-bypass: logic fault {fs['logic_fault_ms']:.1f} ms, board power loss {fs['power_loss_ms']:.0f} ms -> {fs['margin_vs_drdo']:.0f}x inside DRDO's 500 ms.")
    z = sb["zeroize"]
    a(f"Zeroize: {z['fiism_kbit']:.0f} kbit FIISM + buffers in {z['time_us']:.1f} us; hold-up energy margin {z['margin']:.0f}x.")
    a("GNSS-denied: GCS-direction error " + ", ".join(f"{g['err_deg']} deg -> {g['loss_db']:.2f} dB" for g in sb["gnss_denied"]) + ".")
    return "\n".join(L) + "\n"


if __name__ == "__main__":
    main()
